version: "1.0"
info:
  model: int-scaffold
packages:
- name: CredExpiredRepoProject
  gitServerName: Testing
  gitUrl: https://github.com/GitUserMunatri/CredExpiredRepoProject
  gitUsername: GitUserMunatri
  gitBranch: main
